version: '2'
services:
 jenkins:
   build: ./jenkins_docker_dir/
   volumes:
    - ./jenkins_data:/var/jenkins_home
    -  /var/run/docker.sock:/var/run/docker.sock
   ports:
    - 8080:8080
    - 50000:50000


